# Generated by Django 3.2 on 2022-07-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_comment_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='is_draft',
            field=models.BooleanField(default=False, verbose_name='下書き'),
        ),
    ]
